give @s azalea:bindable_1
give @s azalea:bindable_2
give @s azalea:bindable_3
give @s azalea:bindable_4
give @s azalea:bindable_5
give @s azalea:bindable_6
give @s azalea:bindable_7
give @s azalea:bindable_8
give @s azalea:bindable_9
give @s azalea:bindable_10
give @s azalea:bindable_11
give @s azalea:bindable_12
give @s azalea:bindable_13
give @s azalea:bindable_14
give @s azalea:bindable_15
give @s azalea:bindable_16
give @s azalea:bindable_17
give @s azalea:bindable_18
give @s azalea:bindable_19
give @s azalea:bindable_20
give @s azalea:bindable_21
give @s azalea:bindable_22
give @s azalea:bindable_23
give @s azalea:bindable_24
give @s azalea:bindable_25
give @s azalea:bindable_26
give @s azalea:bindable_27
give @s azalea:bindable_28
give @s azalea:bindable_29
give @s azalea:bindable_30
give @s azalea:bindable_31