version: 2.2 Beta 1
folders:
  - scripts
  - items
  - entities
files:
  - pack_icon.png
  - README.md
  - LICENSE
resourcePath: C:\Users\TRASH\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\development_resource_packs\resources
resourceFolders:
  - textures
  - ui
  - texts
  - models
  - attachables
  - animation_controllers
  - entity
  - particles
  - render_controllers
  - font
resourceFiles:
  - blocks.json
  - pack_icon.png
webhook: https://discord.com/api/webhooks/1225229500770422905/K7HYJrSEE__3aqN7xg11sSuJSJua3x594FAM8-f6CEEBwsuZwO8toTfiOIqzV4mVT1k7
stats:
  ver: 282
