version: 2.2 Beta 69420
dev_server:
  port: 19157
  portv6: 19158
  http: 19159
folders:
  - scripts
  - items
  - entities
files:
  - pack_icon.png
  - README.md
  - LICENSE
resourcePath: c:\Users\Zip
  Tie\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\development_resource_packs\resources
resourceFolders:
  - textures
  - ui
  - texts
  - models
  - attachables
  - animation_controllers
  - entity
  - particles
  - render_controllers
  - font
  - animations
resourceFiles:
  - blocks.json
  - pack_icon.png
webhook: https://discord.com/api/webhooks/1230342147371307200/LR1wyqJnWQ2vkHCpdNvxPRYpvefed5AXkIP0VPg4HQcREm_pC2S5DiSwJOrhyoeOLWnf
stats:
  ver: 345
