export const en_us = {
    "teleporting": "Teleporting you to warp: <insert warp name here>",
    "warpNotFound": "Warp not found!",
    "warpAdded": "Warp added!",
    "adminRequired": "This command requires admin",
    "verificationNotEnabled": "No need to verify, verification is not enabled.",
    "verified": "You are now verified!",
    "verificationConfig": "If you are not an admin, tell the admins to configure the verification code, or if you are an admin, configure the verification code.",
    "invalidVerificationCode": "Invalid verification code",
    "alreadyVerified": "You're already verified!",
    "createLocations": "Create locations players can teleport to anytime",
    "warps": "Warps",
    "helpCenter": "Help Center",
    "getAzaleaVersion": "Get the azalea version",
    "management": "Management",
    "getAccess": "Get access",
    "serverUptime": "List server uptime records",
    "info": "Info",
    "noUptimeRecorded": "No recorded uptime!",
    "uptimeRange": "From <TIME> To <OTHER TIME>",
    "toggleCommand": "Toggle a command",
    "defaultPermissions": "Default permissions",
    "adminsOnly": "Admins only",
    "completelyDisabled": "Completely disabled",
    "enabledForEveryone": "Enabled for everyone (BETA)",
    "enabledNote": "Please note that enabled for everyone only works on some commands, and may not work for subcommands",
    "toggleCommandAgain": "Toggle a command",
    "commandRemoved": "Command removed!",
    "commandNotFound": "Command not found!",
    "noCommandName": "You must include a command name",
    "noCommandAndTagName": "You must include a command name and tag name",
    "getHelpWithTagCmd": "Get help with tagcmd",
    "createCustomCommands": "Create custom commands using commands",
    "spawningTadpole": "Spawning tadpole",
    "theTadpole": "THE TADPOLE",
    "playerLeftStaffchat": "<player> left staffchat",
    "playerJoinedStaffchat": "<player> joined staffchat",
    "joinedStaffchat": "Joined staffchat",
    "leftStaffchat": "Left staffchat",
    "enterPrice": "Enter a price",
    "invalidPrice": "Invalid price!",
    "holdingItemRequired": "You need to be holding an item",
    "moveToOpenShopUI": "Move around to open the shop UI",
    "serverInfoNotConfigured": "Server info not configured! If you are an admin, use {/give @s azalea:config_ui}",
    "serverInfo": "Server Info",
    "serverName": "Server name",
    "serverDescription": "Server description",
    "viewServerInfo": "View info about the server",
    "themeApplied": "Theme Applied",
    "randomNumber": "Returns a random number 1 - 5",
    "realHecking": "real hecking",
    "pongResponse": "Says pong",
    "fun": "Fun",
    "partiesNoFriends": "Parties, most likely with 1 person as you have no friends.",
    "partyAlreadyMade": "You already made a party",
    "playerNotOnline": "Player is not online!",
    "playerNoParty": "Player does not own a party.",
    "noPartyToLeave": "There's no party to leave, you probably need to find some friends.",
    "moderation": "Moderation",
    "toggled": "TOGGLED",
    "posted": "Posted!",
    "playerNotFound": "Player not found!",
    "unmutedPlayer": "Unmuted player!",
    "invalidTimeFormat": "Invalid time format! Example: 2h3m5s",
    "unmutedPlayerNotFound": "Player not found!",
    "enchantCommandRequirements": "You must have 2 arguments. Example: !enchant sharpness 50",
    "levelMustBeNumber": "Level must be a number.",
    "enchanted": "Enchanted",
    "error": "Error",
    "infoUp": "INFO",
    "success": "SUCCESS",
    "commandError": "ERROR",
    "warning": "WARNING",
    "response": "RESPONSE",
    "dogSpawned": "Dog successfully spawned",
    "clearChat": "Clears chat",
    "azeleaCreators": "Who helped make azalea",
    "broadcasted": "Broadcasted!",
    "banPlayerMissingName": "You must include a player name. If the player you're trying to ban has spaces in their name, just add quotes around their name.",
    "playerNotFoundForBan": "Could not find player. Make sure the player you're trying to ban is online and if they have spaces in their username, put quotes around their name in the command.",
    "cantBanAdmins": "Can't ban admins",
    "bannedYou": "You have been banned!",
    "playerRankNotFound": "Player does not have that rank! Remember that ranks are case sensitive and color code sensitive."
}